#!/usr/bin/env bash
# Run the fleet's MQTT broker (pixi run fleet-broker).
#
# Mosquitto resolves persistence_file against its working directory, so this
# runs it from the fleet box's state root rather than from the checkout: the
# broker's retained state belongs with the registry database, not in a git tree
# that a redeploy replaces. Same split as the robot's MOTE_HOME.
#
# WEBSOCKETS. M3's dashboard subscribes to the control plane straight from the
# browser, which means the broker needs a `protocol websockets` listener -- and
# conda-forge's mosquitto is built without libwebsockets (measured: it refuses
# to start, docs/fleet/m1-verification.md S4). So there are two ways to run it:
#
#   pixi run fleet-broker       conda's mosquitto; MQTT only when that build has
#                               no websockets, and it says so on startup
#   pixi run fleet-broker-ws    mosquitto in a container, websockets and all --
#                               what the fleet box runs, and it needs no pixi
#                               environment at all
#
# The config is one file either way. This script strips the websockets stanza
# out of a copy when the local binary cannot honour it, rather than shipping two
# configs that drift.
#
# CREDENTIALS (M7). The broker is no longer anonymous: it reads broker/passwd
# and broker/acl under $MOTE_FLEET_HOME, both GENERATED from the registry by the
# fleet server. This script creates them empty if they are missing, so a broker
# started before the server has ever run comes up refusing everyone rather than
# refusing to start -- and `broker.sh reload` is how the server tells a running
# broker to re-read them when a robot enrols or an operator is revoked.
set -euo pipefail

FLEET_HOME="${MOTE_FLEET_HOME:-$HOME/.mote-fleet}"
HERE="$(cd "$(dirname "$0")" && pwd)"
# The shipped config, unless something points elsewhere. A second fleet on one
# box, and the tests, need a listener on another port, and there is no way to
# say that on mosquitto's command line once the file names an explicit listener.
CONF="${MOTE_BROKER_CONF:-$HERE/mosquitto.conf}"
IMAGE="${MOTE_BROKER_IMAGE:-eclipse-mosquitto:2}"
CONTAINER="${MOTE_BROKER_CONTAINER:-mote-broker}"
MODE=local

# How a running broker is told to re-read the generated credential files. The
# mode is recorded at startup because "which broker is running" is not something
# a reload arriving minutes later can work out for itself.
PID_FILE="$FLEET_HOME/broker.pid"
MODE_FILE="$FLEET_HOME/broker.mode"

if [ "${1:-}" = "reload" ]; then
    RUNNING_MODE="$(cat "$MODE_FILE" 2>/dev/null || echo)"
    case "$RUNNING_MODE" in
        docker)
            exec docker kill -s HUP "$CONTAINER"
            ;;
        local)
            PID="$(cat "$PID_FILE" 2>/dev/null || echo)"
            if [ -z "$PID" ] || ! kill -0 "$PID" 2>/dev/null; then
                echo "no running broker at pid '${PID:-<none>}' ($PID_FILE)" >&2
                exit 1
            fi
            exec kill -HUP "$PID"
            ;;
        *)
            echo "no broker started by this script (looked in $MODE_FILE)" >&2
            echo "  the credential files are correct on disk regardless; a" >&2
            echo "  broker started by hand or by systemd needs its own SIGHUP" >&2
            exit 1
            ;;
    esac
fi

if [ "${1:-}" = "--docker" ]; then
    MODE=docker
    shift
fi

mkdir -p "$FLEET_HOME" "$FLEET_HOME/broker"

# Fail closed, and start anyway. An empty password file admits nobody, which is
# the right state for a broker whose fleet server has never run -- as opposed to
# a broker that will not start, which looks like a broken deployment.
for generated in passwd acl; do
    if [ ! -f "$FLEET_HOME/broker/$generated" ]; then
        printf '# Generated by the mote fleet server. Empty: no client may connect.\n' \
            > "$FLEET_HOME/broker/$generated"
        chmod 600 "$FLEET_HOME/broker/$generated"
        echo "  created an empty $FLEET_HOME/broker/$generated — nothing can" >&2
        echo "  connect until the fleet server writes it (start fleet-server, or" >&2
        echo "  run 'fleetctl broker sync')" >&2
    fi
done

if [ "$MODE" = docker ]; then
    if ! command -v docker >/dev/null; then
        echo "no docker on PATH — install it, or run 'pixi run fleet-broker' for" >&2
        echo "an MQTT-only broker (no dashboard; see this script's header)" >&2
        exit 1
    fi
    # --network host: the broker must be reachable at the fleet box's own
    # address (its MagicDNS name is what enrollment hands to every robot), and
    # published ports would put a NAT between the two for no benefit.
    # --user: the image's mosquitto user cannot write a state directory owned by
    # whoever runs this, and the fleet's retained state should stay theirs.
    echo "broker: $IMAGE (docker)   state: $FLEET_HOME   config: $CONF"
    echo docker > "$MODE_FILE"
    exec docker run --rm --name "$CONTAINER" --network host \
        --user "$(id -u):$(id -g)" \
        -v "$CONF:/mosquitto/config/mosquitto.conf:ro" \
        -v "$FLEET_HOME:/mosquitto/data" \
        -w /mosquitto/data \
        "$IMAGE" mosquitto -c /mosquitto/config/mosquitto.conf "$@"
fi

# conda-forge's mosquitto package puts the *broker* in $PREFIX/sbin and only the
# clients (mosquitto_pub/_sub) in bin, and pixi only adds bin to PATH -- so a
# plain `mosquitto` is "command not found" in an environment that definitely has
# it. Look in sbin first, then fall back to PATH for a system install.
BROKER="${CONDA_PREFIX:-}/sbin/mosquitto"
if [ ! -x "$BROKER" ]; then
    BROKER="$(command -v mosquitto || true)"
fi
if [ -z "$BROKER" ]; then
    echo "no mosquitto broker found (looked in \$CONDA_PREFIX/sbin and PATH)" >&2
    exit 1
fi

# Does this build have websockets? One built against libwebsockets links it; one
# that is not fails at config-parse time with "Websockets support not
# available", which is a worse way to find out.
RUNTIME_CONF="$CONF"
if ldd "$BROKER" 2>/dev/null | grep -q websockets; then
    echo "broker: $BROKER (websockets)   state: $FLEET_HOME   config: $CONF"
else
    RUNTIME_CONF="$FLEET_HOME/mosquitto.no-ws.conf"
    sed '/^# >>> websockets/,/^# <<< websockets/d' "$CONF" >"$RUNTIME_CONF"
    echo "broker: $BROKER (NO websockets)   state: $FLEET_HOME   config: $RUNTIME_CONF"
    echo "  the fleet dashboard needs MQTT-over-WebSockets and this build has" >&2
    echo "  none — run 'pixi run fleet-broker-ws' instead for the container" >&2
    echo "  broker. Robots, fleetctl and the fleet API are unaffected." >&2
fi

cd "$FLEET_HOME"
# `exec` keeps this shell's pid, so $$ is the broker's pid once it replaces us —
# which is what `broker.sh reload` sends its SIGHUP to.
echo local > "$MODE_FILE"
echo $$ > "$PID_FILE"
exec "$BROKER" -c "$RUNTIME_CONF" "$@"
