"""Hardware facts a robot presents at enrollment, and the fingerprint from them.

The fingerprint is what makes enrollment **idempotent**: the server keys its
registry row on it, so re-running ``enroll`` — after a re-image, after a wiped
``~/.mote``, after a botched first attempt — returns the *same* ``robot_id``
rather than minting a second fleet member for the same physical robot. That is
the property identity.py promises ("re-imaging a Pi must not silently mint a new
fleet member") and it can only be kept by something that outlives the disk.

Sources, in the order they are trusted:

``machine-id``
    ``/etc/machine-id``. Stable across reboots and across our own software
    updates, but *regenerated by a fresh OS install* — which is the honest
    behaviour: a re-imaged card really is a new install, and the operator
    re-enrolls it onto the same id by passing ``--id``.
``serial``
    The Pi's SoC serial from ``/proc/cpuinfo`` — genuinely tied to the board, so
    it survives re-imaging. Preferred where it exists, which is every robot.
``mac``
    The first non-loopback interface's MAC. Last resort: it moves with a USB
    adapter and is trivially spoofed.

All three are collected and stored on the row for audit; only the best one is
the fingerprint. Everything here is best-effort — a missing source yields an
empty string rather than an exception, because a robot that cannot read
``/proc/cpuinfo`` should still be able to enroll.
"""

import os
import platform
import re
import socket
import uuid
from pathlib import Path

SERIAL_RE = re.compile(r"^Serial\s*:\s*([0-9a-fA-F]+)", re.MULTILINE)
MODEL_RE = re.compile(r"^Model\s*:\s*(.+)$", re.MULTILINE)


def _read(path: str) -> str:
    try:
        return Path(path).read_text().strip()
    except OSError:
        return ""


def machine_id() -> str:
    return _read("/etc/machine-id") or _read("/var/lib/dbus/machine-id")


def cpuinfo_field(pattern: re.Pattern) -> str:
    match = pattern.search(_read("/proc/cpuinfo"))
    return match.group(1).strip() if match else ""


def mac() -> str:
    """The primary interface's MAC as ``aa:bb:...``, or "" if it looks random.

    ``uuid.getnode()`` sets the multicast bit when it had to invent an address,
    which is exactly the case where it must not become a fingerprint.
    """
    node = uuid.getnode()
    if node >> 40 & 0x01:
        return ""
    return ":".join(f"{(node >> shift) & 0xFF:02x}" for shift in range(40, -8, -8))


def collect() -> dict:
    """Everything the server should record about this machine."""
    return {
        "machine_id": machine_id(),
        "serial": cpuinfo_field(SERIAL_RE),
        "mac": mac(),
        "hostname": socket.gethostname(),
        "model": cpuinfo_field(MODEL_RE) or platform.machine(),
        "os": f"{platform.system()} {platform.release()}",
        "user": os.environ.get("USER", ""),
    }


def fingerprint(collected: dict) -> str:
    """The stable key the registry rows are matched on, ``<kind>:<value>``."""
    for kind in ("serial", "machine_id", "mac"):
        value = (collected.get(kind) or "").strip().lower()
        if value:
            return f"{kind}:{value}"
    raise ValueError(
        "no stable hardware identifier on this machine (no SoC serial, no "
        "machine-id, no usable MAC) — enroll with an explicit --id instead"
    )
